//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int Expense_Id { get; set; }
        public int category_Id { get; set; }
        public string Details { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Expense_Information Expense_Information { get; set; }
    }
}
