//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine_Information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine_Information()
        {
            this.Batches = new HashSet<Batch>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int ID { get; set; }
        public string Medicine_Name { get; set; }
        public int Generic_ID { get; set; }
        public int Manufacturer_ID { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> UnitId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual Drug_Generic_name Drug_Generic_name { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
