//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.Batches = new HashSet<Batch>();
        }
    
        public int ID { get; set; }
        public string Purchase_ID { get; set; }
        public decimal Amount { get; set; }
        public int Discount { get; set; }
        public decimal Discount_Amount { get; set; }
        public decimal Grand_Total { get; set; }
        public string IsPaid { get; set; }
        public System.DateTime Entry_Date { get; set; }
        public string Description { get; set; }
        public int Supplier_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
