//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public int Quantity { get; set; }
        public decimal Cost { get; set; }
        public decimal Amount { get; set; }
        public int Medicine_ID { get; set; }
        public string Bill_Invoice { get; set; }
    
        public virtual Bill_Information Bill_Information { get; set; }
        public virtual Medicine_Information Medicine_Information { get; set; }
    }
}
